# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rl_agent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erl_agent.proto\x12\x08rl_agent\"e\n\nBatchState\x12\x12\n\nbatch_size\x18\x01 \x01(\r\x12\x14\n\x0c\x62\x61tch_age_ms\x18\x02 \x01(\x02\x12\x17\n\x0fupstream_p99_ms\x18\x03 \x01(\x02\x12\x14\n\x0crequest_rate\x18\x04 \x01(\x02\"%\n\rFlushDecision\x12\x14\n\x0cshould_flush\x18\x01 \x01(\x08\x32\x42\n\x07RlAgent\x12\x37\n\x06\x44\x65\x63ide\x12\x14.rl_agent.BatchState\x1a\x17.rl_agent.FlushDecisionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rl_agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATCHSTATE']._serialized_start=28
  _globals['_BATCHSTATE']._serialized_end=129
  _globals['_FLUSHDECISION']._serialized_start=131
  _globals['_FLUSHDECISION']._serialized_end=168
  _globals['_RLAGENT']._serialized_start=170
  _globals['_RLAGENT']._serialized_end=236
# @@protoc_insertion_point(module_scope)
