# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rl_agent_pb2 as rl__agent__pb2


class RlAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/rl_agent.RlAgent/Decide',
                request_serializer=rl__agent__pb2.BatchState.SerializeToString,
                response_deserializer=rl__agent__pb2.FlushDecision.FromString,
                )


class RlAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Decide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RlAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=rl__agent__pb2.BatchState.FromString,
                    response_serializer=rl__agent__pb2.FlushDecision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl_agent.RlAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RlAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rl_agent.RlAgent/Decide',
            rl__agent__pb2.BatchState.SerializeToString,
            rl__agent__pb2.FlushDecision.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
